/*
 * This file is generated by jOOQ.
 */
package gensrc.tables.records;


import gensrc.tables.RoleMaster;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoleMasterRecord extends UpdatableRecordImpl<RoleMasterRecord> implements Record4<Integer, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1842716152;

    /**
     * Setter for <code>role_master.role_id</code>.
     */
    public void setRoleId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>role_master.role_id</code>.
     */
    public Integer getRoleId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>role_master.role</code>.
     */
    public void setRole(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>role_master.role</code>.
     */
    public String getRole() {
        return (String) get(1);
    }

    /**
     * Setter for <code>role_master.created_on</code>.
     */
    public void setCreatedOn(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>role_master.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>role_master.updated_on</code>.
     */
    public void setUpdatedOn(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>role_master.updated_on</code>.
     */
    public LocalDateTime getUpdatedOn() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return RoleMaster.ROLE_MASTER.ROLE_ID;
    }

    @Override
    public Field<String> field2() {
        return RoleMaster.ROLE_MASTER.ROLE;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return RoleMaster.ROLE_MASTER.CREATED_ON;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return RoleMaster.ROLE_MASTER.UPDATED_ON;
    }

    @Override
    public Integer component1() {
        return getRoleId();
    }

    @Override
    public String component2() {
        return getRole();
    }

    @Override
    public LocalDateTime component3() {
        return getCreatedOn();
    }

    @Override
    public LocalDateTime component4() {
        return getUpdatedOn();
    }

    @Override
    public Integer value1() {
        return getRoleId();
    }

    @Override
    public String value2() {
        return getRole();
    }

    @Override
    public LocalDateTime value3() {
        return getCreatedOn();
    }

    @Override
    public LocalDateTime value4() {
        return getUpdatedOn();
    }

    @Override
    public RoleMasterRecord value1(Integer value) {
        setRoleId(value);
        return this;
    }

    @Override
    public RoleMasterRecord value2(String value) {
        setRole(value);
        return this;
    }

    @Override
    public RoleMasterRecord value3(LocalDateTime value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public RoleMasterRecord value4(LocalDateTime value) {
        setUpdatedOn(value);
        return this;
    }

    @Override
    public RoleMasterRecord values(Integer value1, String value2, LocalDateTime value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoleMasterRecord
     */
    public RoleMasterRecord() {
        super(RoleMaster.ROLE_MASTER);
    }

    /**
     * Create a detached, initialised RoleMasterRecord
     */
    public RoleMasterRecord(Integer roleId, String role, LocalDateTime createdOn, LocalDateTime updatedOn) {
        super(RoleMaster.ROLE_MASTER);

        set(0, roleId);
        set(1, role);
        set(2, createdOn);
        set(3, updatedOn);
    }
}
