/*
 * This file is generated by jOOQ.
 */
package gensrc;


import gensrc.tables.RoleMaster;
import gensrc.tables.UserMaster;


/**
 * Convenience access to all tables in 
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>role_master</code>.
     */
    public static final RoleMaster ROLE_MASTER = RoleMaster.ROLE_MASTER;

    /**
     * The table <code>user_master</code>.
     */
    public static final UserMaster USER_MASTER = UserMaster.USER_MASTER;
}
