/*
 * This file is generated by jOOQ.
 */
package gensrc.tables.daos;


import gensrc.tables.UserMaster;
import gensrc.tables.records.UserMasterRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserMasterDao extends DAOImpl<UserMasterRecord, gensrc.tables.pojos.UserMaster, Integer> {

    /**
     * Create a new UserMasterDao without any configuration
     */
    public UserMasterDao() {
        super(UserMaster.USER_MASTER, gensrc.tables.pojos.UserMaster.class);
    }

    /**
     * Create a new UserMasterDao with an attached configuration
     */
    public UserMasterDao(Configuration configuration) {
        super(UserMaster.USER_MASTER, gensrc.tables.pojos.UserMaster.class, configuration);
    }

    @Override
    public Integer getId(gensrc.tables.pojos.UserMaster object) {
        return object.getUserId();
    }

    /**
     * Fetch records that have <code>user_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<gensrc.tables.pojos.UserMaster> fetchRangeOfUserId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(UserMaster.USER_MASTER.USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<gensrc.tables.pojos.UserMaster> fetchByUserId(Integer... values) {
        return fetch(UserMaster.USER_MASTER.USER_ID, values);
    }

    /**
     * Fetch a unique record that has <code>user_id = value</code>
     */
    public gensrc.tables.pojos.UserMaster fetchOneByUserId(Integer value) {
        return fetchOne(UserMaster.USER_MASTER.USER_ID, value);
    }

    /**
     * Fetch records that have <code>first_name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<gensrc.tables.pojos.UserMaster> fetchRangeOfFirstName(String lowerInclusive, String upperInclusive) {
        return fetchRange(UserMaster.USER_MASTER.FIRST_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>first_name IN (values)</code>
     */
    public List<gensrc.tables.pojos.UserMaster> fetchByFirstName(String... values) {
        return fetch(UserMaster.USER_MASTER.FIRST_NAME, values);
    }

    /**
     * Fetch records that have <code>last_name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<gensrc.tables.pojos.UserMaster> fetchRangeOfLastName(String lowerInclusive, String upperInclusive) {
        return fetchRange(UserMaster.USER_MASTER.LAST_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_name IN (values)</code>
     */
    public List<gensrc.tables.pojos.UserMaster> fetchByLastName(String... values) {
        return fetch(UserMaster.USER_MASTER.LAST_NAME, values);
    }

    /**
     * Fetch records that have <code>user_name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<gensrc.tables.pojos.UserMaster> fetchRangeOfUserName(String lowerInclusive, String upperInclusive) {
        return fetchRange(UserMaster.USER_MASTER.USER_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_name IN (values)</code>
     */
    public List<gensrc.tables.pojos.UserMaster> fetchByUserName(String... values) {
        return fetch(UserMaster.USER_MASTER.USER_NAME, values);
    }

    /**
     * Fetch records that have <code>password BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<gensrc.tables.pojos.UserMaster> fetchRangeOfPassword(String lowerInclusive, String upperInclusive) {
        return fetchRange(UserMaster.USER_MASTER.PASSWORD, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<gensrc.tables.pojos.UserMaster> fetchByPassword(String... values) {
        return fetch(UserMaster.USER_MASTER.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>is_deleted BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<gensrc.tables.pojos.UserMaster> fetchRangeOfIsDeleted(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(UserMaster.USER_MASTER.IS_DELETED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>is_deleted IN (values)</code>
     */
    public List<gensrc.tables.pojos.UserMaster> fetchByIsDeleted(Boolean... values) {
        return fetch(UserMaster.USER_MASTER.IS_DELETED, values);
    }

    /**
     * Fetch records that have <code>created_on BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<gensrc.tables.pojos.UserMaster> fetchRangeOfCreatedOn(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(UserMaster.USER_MASTER.CREATED_ON, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_on IN (values)</code>
     */
    public List<gensrc.tables.pojos.UserMaster> fetchByCreatedOn(LocalDateTime... values) {
        return fetch(UserMaster.USER_MASTER.CREATED_ON, values);
    }

    /**
     * Fetch records that have <code>updated_on BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<gensrc.tables.pojos.UserMaster> fetchRangeOfUpdatedOn(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(UserMaster.USER_MASTER.UPDATED_ON, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_on IN (values)</code>
     */
    public List<gensrc.tables.pojos.UserMaster> fetchByUpdatedOn(LocalDateTime... values) {
        return fetch(UserMaster.USER_MASTER.UPDATED_ON, values);
    }

    /**
     * Fetch records that have <code>role_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<gensrc.tables.pojos.UserMaster> fetchRangeOfRoleId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(UserMaster.USER_MASTER.ROLE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>role_id IN (values)</code>
     */
    public List<gensrc.tables.pojos.UserMaster> fetchByRoleId(Integer... values) {
        return fetch(UserMaster.USER_MASTER.ROLE_ID, values);
    }
}
