/*
 * This file is generated by jOOQ.
 */
package com.jooq;


import com.jooq.tables.UserMaster;
import com.jooq.tables.records.UserMasterRecord;

import org.jooq.Identity;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<UserMasterRecord, Integer> IDENTITY_USER_MASTER = Identities0.IDENTITY_USER_MASTER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<UserMasterRecord> CONSTRAINT_E = UniqueKeys0.CONSTRAINT_E;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<UserMasterRecord, Integer> IDENTITY_USER_MASTER = Internal.createIdentity(UserMaster.USER_MASTER, UserMaster.USER_MASTER.USER_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<UserMasterRecord> CONSTRAINT_E = Internal.createUniqueKey(UserMaster.USER_MASTER, "CONSTRAINT_E", new TableField[] { UserMaster.USER_MASTER.USER_ID }, true);
    }
}
