/*
 * This file is generated by jOOQ.
 */
package com.jooq;


import com.jooq.tables.UserMaster;


/**
 * Convenience access to all tables in 
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>user_master</code>.
     */
    public static final UserMaster USER_MASTER = UserMaster.USER_MASTER;
}
